version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "kcs-test" 
region = "eu-central-1"
confirm_changeset = true
fail_on_empty_changeset = false
capabilities = "CAPABILITY_IAM"
s3_bucket = "karaokemp-artifacts"
s3_prefix = "karaokemp-website/kcs-test"
