version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "kcs-test"
s3_prefix = "kcs-test"
region = "eu-central-1"
confirm_changeset = false
fail_on_empty_changeset = false
capabilities = "CAPABILITY_IAM"
