version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "karaokemp-backend-services"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-12j1cok899yq8"
s3_prefix = "karaokemp-backend-services"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
