version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "karaokemp-cloud-services"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-jhbkne7wmc8b"
s3_prefix = "karaokemp-cloud-services"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"Test\""
