AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description:
  Karaokemp Cloud Services

Globals:
  Function:
    Timeout: 3

Resources:
  KaraokeSongsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-karaoke-songs"

  FrontendBucket:
    Type:  AWS::S3::Bucket
    Properties:
      BucketName:  !Sub "${AWS::StackName}-website-frontend"  
  SongsApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration: True
  ListSongsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: ./functions/list-songs/app.lambdaHandler
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 5
      Events:
        ListSongs:
          Type: HttpApi
          Properties:
            ApiId: !Ref SongsApi
            Method: GET
            Path: /songs
Outputs:
  URL:
    Description: URL for List Songs Function
    Value: !Sub "https://${SongsApi}.execute-api.${AWS::Region}.amazonaws.com/songs"