AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description:
  Karaokemp Cloud Services

Globals:
  Function:
    Timeout: 3

Resources:
  SongsApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration: True
  ListSongsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: ./functions/list-songs/app.lambdaHandler
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 5
      Events:
        ListSongs:
          Type: HttpApi
          Properties:
            ApiId: !Ref SongsApi
            Method: GET
            Path: /songs
  KaraokeSongsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-karaoke-songs"
      AccessControl: PublicRead

  FrontendBucket:
    Type:  AWS::S3::Bucket
    Properties:
      BucketName:  !Sub "${AWS::StackName}-website-frontend"
      AccessControl: PublicRead
      WebsiteConfiguration:
        ErrorDocument: 'index.html'
        IndexDocument: 'index.html'
Outputs:
  Website:
    Description: Public Website URL
    Value: !GetAtt [FrontendBucket, WebsiteURL]
  SongsBucket:
    Description: Bucket Phisical Name
    Value: !Sub "${AWS::StackName}-karaoke-songs"
  SongsBucketURL:
    Value: !Join ['', ['https://', !GetAtt [KaraokeSongsBucket, DomainName]]]
    Description: Name of S3 bucket to hold website content
  Function:
    Description: List Songs Function URL
    Value: !Sub "https://${SongsApi}.execute-api.${AWS::Region}.amazonaws.com/songs"

