AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Karaokemp services needed to be available online
  
Globals:
  Function:
    Timeout: 3

Resources:
  BoardHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      #StageName: Test
      CorsConfiguration: True
  GetMessagesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: ./functions/list-songs/app.lambdaHandler
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 5
      Events:
        GetMessages:
          Type: HttpApi
          Properties:
            ApiId: !Ref BoardHttpApi
            Method: GET
            Path: /messages
   
      Policies:
   
        - AmazonDynamoDBFullAccess