AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description:
  Karaokemp services needed to be available online
  
Globals:
  Function:
    Timeout: 3

Resources:
  BoardHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: Test
      CorsConfiguration: True
  GetMessagesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: ./list-songs/app.lambdaHandler
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 5
      Events:
        GetMessages:
          Type: HttpApi
          Properties:
            ApiId: !Ref BoardHttpApi
            Method: GET
            Path: /songs
  Outputs:
    ListSongsApi:
      Description: "API Gateway endpoint URL for Prod stage for List Songs function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Test/songs/"
    ListSongsFunction:
      Description: "List Songs Lambda Function ARN"
      Value: !GetAtt ListSongsFunction.Arn
    ListSongsFunctionIamRole:
      Description: "Implicit IAM Role created for List Songs function"
      Value: !GetAtt ListSongsFunctionRole.Arn