version: "3.3"
services:
  frontend:
    image: dreckguy/karaokemp-website-frontend    
    ports:
      - 80:80
  backend:
    image: dreckguy/karaokemp-website-backend
    ports:
      - 4000:4000
    volumes:
      - "./songs:/usr/src/app/songs"
  