version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "karaokemp-website-services"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-cfbd33m8sc3f"
s3_prefix = "karaokemp-website-services"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
